-- Migration: Add reserved_by column to ticket_activations for GDPR Art. 17 compliance
-- Issue: #1385 — delete-my-account omits unactivated tickets generated by the deleted user
-- Created: 2026-06-28

-- Add the column as nullable with a FK to auth.users so it can be backfilled
-- to NULL for existing rows (pre-migration tickets have no generating-user record).
-- ON DELETE SET NULL preserves the row if the generating user is deleted via
-- auth.admin.deleteUser() before the Edge Function deletes the data — the
-- delete-my-account function deletes rows WHERE reserved_by = userId before
-- calling deleteUser(), so this FK should only be needed as a safety net.
alter table public.ticket_activations
  add column if not exists reserved_by uuid references auth.users(id) on delete set null;

-- Index to make the delete-my-account cleanup query efficient.
create index if not exists ticket_activations_reserved_by_idx
  on public.ticket_activations(reserved_by)
  where reserved_by is not null;

comment on column public.ticket_activations.reserved_by is
  'auth.users.id of the admin who generated this ticket via reserve_hash. '
  'Used during account deletion to remove unactivated tickets (GDPR Art. 17, closes #1385). '
  'NULL for tickets generated before this column was added.';
